# infra/cloud-init.yaml
#cloud-config
packages:
  - docker.io
  - git
  - curl
runcmd:
  - usermod -aG docker ubuntu
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - install kubectl /usr/local/bin/
  - echo "Cloud-init terminé"
