# k8s/sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: devops-portfolio
spec:
  encryptedData:
    username: AgBfJHn...  # valeur chiffrée
    password: AbCdEf...  # valeur chiffrée
  template:
    type: Opaque
